- hosts: all
  sudo: yes
  vars_files:
    - vars/moinmoin.yml
  tasks:

    - name: backup
      shell: cd /opt/moin/wiki && sudo tar zvcf /tmp/moin-data-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}.tar.gz data

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Ensure /opt exists
      file: path=/opt state=directory

    - name: Download moin tarball
      get_url: url=http://static.moinmo.in/files/moin-{{ moin_version }}.tar.gz dest=/tmp/moin-{{ moin_version }}.tar.gz
    - name: Unarchive tarball
      unarchive: src=/tmp/moin-{{ moin_version }}.tar.gz dest=/opt copy=no creates=/opt/moin-{{ moin_version }}
    - name: Change permission
      file: path=/opt/moin-{{ moin_version }} owner=www-data group=www-data recurse=yes
    - name: symlinking
      file: path=/opt/moin state=link src=/opt/moin-{{ moin_version }}

    - name: Install apache2
      apt: name=apache2

    - template: src=etc/apache2/sites-available/moinmoin.conf dest=/etc/apache2/sites-available/moinmoin.conf
      notify: reload apache2

    # Enable site and each module
    - command: a2ensite moinmoin
    - apache2_module: name=rewrite
    - apache2_module: name=proxy
    - apache2_module: name=proxy_http

    # Basic auth
    - name: Install passlib for ansible/htpasswd
      apt: name=python-passlib
    - name: Basic auth
      htpasswd: name="{{ basic_auth_user }}" password="{{ basic_auth_password }}" path=/etc/apache2/.htpasswd

    - name: reload apache2
      service: name=apache2 state=reloaded

    - name: Install supervisord
      apt: name=supervisor
    - copy: src=etc/supervisor/conf.d/moinmoin.conf dest=/etc/supervisor/conf.d/moinmoin.conf

    # moinmoin configuration
    - lineinfile: dest=/opt/moin/wikiconfig.py line="    page_front_page = u\"Home\"" insertafter="class LocalConfig"
    - lineinfile: dest=/opt/moin/wikiconfig.py line="    mail_from = u\"{{ mail_from }}\"" insertafter="class LocalConfig"
    - lineinfile: dest=/opt/moin/wikiconfig.py line="    mail_sendmail = u\"/usr/sbin/sendmail -t -i\"" insertafter="class LocalConfig"

    # moinmoin markdown plugin
    - apt: name=python-markdown
    - copy: src=opt/moin/wiki/data/plugin/parser/text_markdown.py dest=/opt/moin/wiki/data/plugin/parser/text_markdown.py
    - lineinfile: dest=/opt/moin/MoinMoin/web/static/htdocs/modernized/css/common.css line="@import url(\"codehilite.css\");" insertbefore=BOF
    - copy: src=opt/moin/MoinMoin/web/static/htdocs/modernized/css/codehilite.css dest=/opt/moin/MoinMoin/web/static/htdocs/modernized/css/codehilite.css

    - name: reload moinmoin
      command: supervisorctl restart moinmoin
